### ISSUE TITLE
Bug: Rerolling leaves items currently in crafting window, or held on cursor

### ISSUE THREAD

**Issue by Timiryazev** [SmashingModsTogether/Reroll#2]
![image](https://user-images.githubusercontent.com/15707879/157962219-35bbdaa3-30f7-49ef-9209-fec456e92bff.png)
Picture taken immediately after rerolling via server command

**Comment by Timiryazev** [comment]
The shovel's currently held on my cursor, that's why it's floating.

**Comment by Dark-Arcana** [comment]
Thanks for this. I'm wondering if called `entityPlayer.inventory.dropAllItems()` will fix it.

**Comment by Dark-Arcana** [comment]
Fixed in 047c939cc0ab505951a50f787b29540d6a08572b
