### ISSUE TITLE
Feature: Integration with Game Stages

### ISSUE THREAD

**Issue by Timiryazev** [SmashingModsTogether/Reroll#5]
https://www.curseforge.com/minecraft/mc-mods/game-stages

Rerolling should reset your Game Stage

**Comment by CalaMariGold** [comment]
There's a command for this, but it creates a message in chat which is annoying, maybe the message won't show up if the lang for it is removed?

/gamestage clear @p

**Comment by Dark-Arcana** [comment]
Support added in 3a786237ce740f5da99e29e16cc7a7804222fce1

knowing that there are built in commands makes this way easier lol.
