### ISSUE TITLE
Feature: Reroll should reset current Enchanting options.

### ISSUE THREAD

**Issue by Timiryazev** [SmashingModsTogether/Reroll#6]
Current function: Checking an enchanting table for enchantments, then rerolling, gives the same enchantments.

Feature: If there's a way to increment the current enchanting RNG when rerolling, that would be a nice QOL

**Comment by Dark-Arcana** [comment]
I don't think this is possible in. There is no data stored for this value and no public setter. I checked in `EntityPlayerMP`, `MinecraftServer`, and `World` which are places where you might expect to see this. So to make it possible, I would probably have to make custom enchantment code and override the class being used to handle enchantments.
