### ISSUE TITLE
Feature: Mod should be able to function server-side only.

### ISSUE THREAD

**Issue by Timiryazev** [SmashingModsTogether/Reroll#7]
Currently, it's not possible to join a server running the mod, without the mod installed. I know that the in-game command autocomplete won't work without the mod installed, but it'd be nice to only need to add this to a server.

**Comment by Dark-Arcana** [comment]
I might be able to make a packet that can send auto-complete info.

**Comment by Dark-Arcana** [comment]
This should be fixed. The sender will now get a player list from the server that the sender is on. So this works in single player with the integrated server and in multiplayer.

Fixed in c50acaa9a53ebbaa4f7a9af43c99967cdc07ab15
