### ISSUE TITLE
Feature: Reroll Lock

### ISSUE THREAD

**Issue by Timiryazev** [SmashingModsTogether/Reroll#8]
Add an additional command, something like `/lockreroll true` that permanently disables the reroll

I'm sure it could be disabled/enabled wholesale via config, but being able to enable/disable the entire mod by OP or server command could be useful.

Reason: I'm looking into future uses for this function beyond Trepidation. I think it'd be useful on multiplayer for people who want to "scout" a good spawn location for a community server, or the like. My vision is: You start up a new community server, you join as OP, you use `/reroll` to scout out spawn locations for the server, and once you've got a location you like for the world spawn, you can use `/lockreroll` to "set" that location as the permanent world spawn.

**Comment by Drullkus** [comment]
For toggling it in-game, this feature could be implemented as a gamerule

**Comment by Dark-Arcana** [comment]
A gamerule is universal while what I have implemented (upcoming commit) allows an admin to lock/unlock the command on a per player basis.

**Comment by Dark-Arcana** [comment]
Added this feature in f6819c2bf1fed051bb9d2670224792dca6259c72 !
