### ISSUE TITLE
Feature: Integration with Ender Skills

### ISSUE THREAD

**Issue by CalaMariGold** [SmashingModsTogether/Reroll#9]
https://www.curseforge.com/minecraft/mc-mods/ender-skills

All stored EL, reset chances, and unlocked skills should be reset.

**Comment by CalaMariGold** [comment]
Just found out there are commands that set/reset skills, EL, and reset chances.

**Comment by CalaMariGold** [comment]
Those commands being

/es_advancement @p retries set 0
/es_advancement @p level set 1
/es_skill @p reset

**Comment by Dark-Arcana** [comment]
That's helpful. I will investigate it.

**Comment by Dark-Arcana** [comment]
Support added in 3a786237ce740f5da99e29e16cc7a7804222fce1

knowing that there are built in commands makes this way easier lol.
